# Generated by Django 5.2.8 on 2025-12-01 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='ip_datename',
            new_name='ip_datetime',
        ),
    ]
